version: '2'

# Define the services/containers to be run
services:
  chatoyant: #name of your service
    build: ./ # specify the directory of the Dockerfile
    ports:
      - "8080:8080" #specify ports forwarding
    volumes:
      - .:/usr/src/app